### ISSUE TITLE
Does it work on OSX? 

### ISSUE THREAD

**Issue by mindreframer** [rickihastings/cssmate#1]
first things first: I like the idea of having one multiplatform tool to reload CSS and GO is fantastic language for that. 

But I can not get it to work on OSX.... 

Steps to reproduce: 

```
$ cd /tmp
$ git clone https://github.com/rickihastings/cssmate
$ cd cssmate
$ go build -o bin/cssmate
$ ./bin/cssmate --path /path/to/output/from-libsass/
```

file changes, but I see no output from cssmate process

Also: 
- Hardcoded hostname: 
  https://github.com/rickihastings/cssmate/blob/master/public/cssmate.js#L14
    10.0.33.34
- No output, like: 
  - listening for changes in /my/path
- CSS/JS in not bundled into the binary (can't start cssmate from anywhere)
  - https://github.com/jteeuwen/go-bindata could be useful

Maybe we can fix it together, I'd like to contibute, nice and simple apps are great! 

Is there something Linux-y and not OSX-y, that you're using?

**Comment by rickihastings** [comment]
Ahh thanks for pointing these out, great spots.

I'll hopefully get round to fixing the minor issues today and bundle the javascript into the binary, however I've got a very busy day so it will be when I get round to it. I'm happy to accept any pull requests.

As far as OSX goes I'll look into it, however I don't have access to an OSX machine right now. And yes I develop on a Debian virtual machine.

**Comment by mindreframer** [comment]
OK, maybe I will take a look at it also myself. Thx for the quick response!

On Fri, May 9, 2014 at 11:29 AM, Ricki Hastings notifications@github.comwrote:

> Ahh thanks for pointing these out, great spots.
> 
> I'll hopefully get round to fixing the minor issues today and bundle the
> javascript into the binary, however I've got a very busy day so it will be
> when I get round to it. I'm happy to accept any pull requests.
> 
> As far as OSX goes I'll look into it, however I don't have access to an
> OSX machine right now. And yes I develop on a Debian virtual machine.
> 
> > On 9 May 2014, at 10:00, Roman Heinrich notifications@github.com
> > wrote:
> > 
> > first things first: I like the idea of having one multiplatform tool to
> > reload CSS and GO is fantastic language for that.
> > 
> > But I can not get it to work on OSX....
> > 
> > Steps to reproduce:
> > 
> > $ cd /tmp
> > $ git clone https://github.com/rickihastings/cssmate
> > $ cd cssmate
> > $ go build -o bin/cssmate
> > $ ./bin/cssmate --path /path/to/output/from-libsass/
> > file changes, but I see no output from cssmate process
> > 
> > Also:
> > 
> > Hardcoded hostname:
> > https://github.com/rickihastings/cssmate/blob/master/public/cssmate.js#L1410.0.33.34
> > No output, like:
> > listening for changes in /my/path
> > CSS/JS in not bundled into the binary (can't start cssmate from
> > anywhere)
> > Maybe we can fix it together, I'd like to contibute, nice and simple
> > apps are great!
> > 
> > Is there something Linux-y and not OSX-y, that you're using?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rickihastings/cssmate/issues/1#issuecomment-42648333
> .

## 

---

  Roman Heinrich

  Email roman.heinrich@gmail.com
  Github github.com/mindreframer
  Twitter @mindreframer
  Blog devopsbox.es
  Xing xing.to/mindreframer
  Linkedin de.linkedin.com/in/mindreframer
  Resume devopsbox.es/resume/resume.html
  Delicious delicious.com/mindreframer
  Skype mindreframer

**Comment by rickihastings** [comment]
No worries. I have a little bit of downtime right now. Going to to work on your suggestions. I'm not sure where to start with OSX though. Will look into that.

**Comment by mindreframer** [comment]
I guess this can be closed now.
